### ISSUE TITLE
Symbol’s function definition is void: org-roam-capture--find-file-h

### ISSUE THREAD

**Issue by asberk** [org-roam/org-roam-bibtex#86] opened 2020-07-28 17:58 UTC
### Description

At various points I get one of the following errors. Either:

> run-hooks: Symbol’s function definition is void: org-roam-capture--find-file-h

or

> user-error: Symbol’s function definition is void: org-roam-capture--find-file-h.  Please adjust ‘org-roam-capture-templates’

It seems the function `org-roam-capture--find-file-h` does not exist. It appears this non-existent function is added to `org-capture-after-finalize-hook` on line 536 of org-roam-bibtex.el version 0.2.3. 

What is the recommended fix for this issue?

#### Steps to Reproduce

The first error message appears when I try to Edit Notes in the `helm-bibtex` interface for a reference which does not yet have a notes file created for it. The second happens when I `org-roam-insert-immediate` a note that does not yet exist. 

#### Backtrace

I tried to `toggle-debug-on-error`; however, it appears that the above issues do not qualify as "errors". I tried using `debug-on-entry` instead, and the best I could get was:

```
Debugger entered--returning value: (org-roam-capture--finalize org-roam-capture--find-file-h)
  default-value(org-capture-after-finalize-hook)
* remove-hook(org-capture-after-finalize-hook org-roam-capture--finalize)
* #f(compiled-function () #<bytecode 0x438cff71>)()
* apply(#f(compiled-function () #<bytecode 0x438cff71>) nil)
* org-roam-capture--finalize()
  run-hooks(org-capture-after-finalize-hook)
  #f(compiled-function (&optional stay-with-capture) "Finalize the capture process.\nWith prefix argument STAY-WITH-CAPTURE, jump to the location of the\ncaptured item after finalizing." (interactive "P") #<bytecode 0x4b233055>)()
  apply(#f(compiled-function (&optional stay-with-capture) "Finalize the capture process.\nWith prefix argument STAY-WITH-CAPTURE, jump to the location of the\ncaptured item after finalizing." (interactive "P") #<bytecode 0x4b233055>) nil)
  org-capture-finalize()
  org-capture(nil "d")
  org-roam-capture--capture()
  org-roam-insert(nil)
  apply(org-roam-insert nil)
  org-roam-insert-immediate(nil)
  funcall-interactively(org-roam-insert-immediate nil)
  #<subr call-interactively>(org-roam-insert-immediate nil nil)
  apply(#<subr call-interactively> org-roam-insert-immediate (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> org-roam-insert-immediate nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (org-roam-insert-immediate nil nil))
  call-interactively(org-roam-insert-immediate nil nil)
  command-execute(org-roam-insert-immediate)
``` 

### Environment

- Emacs: GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109))
 of 2019-09-02
- Framework: N/A
- Org: Org mode version 9.3.6 (9.3.6-elpa @ /Users/aberk/.emacs.d/elpa/org-9.3.6/)
- Org-roam: 1.2.1

**Comment by zaeph** [comment] 2020-07-28 18:07
Caused by org-roam/org-roam/pull/966.

Problematic area:
https://github.com/org-roam/org-roam-bibtex/blob/b0e2c23a590ad09120960f39353c4c6f879a97b4/org-roam-bibtex.el#L535-L536

I'll investigate how to adapt it.  Thanks for reporting it!

**Comment by zaeph** [comment] 2020-07-28 18:14
Should be fixed, now.  Make sure to update the package.

**Closed** 2020-07-28 18:14 UTC
Labels: bug
