### ISSUE TITLE
Error when creating a note with `author-or-editor` set for preformatting and `author` and `editor` fields missing from BibTeX entry

### ISSUE THREAD

**Issue by bepolymathe** [org-roam/org-roam-bibtex#83] opened 2020-07-16 12:46 UTC
Hi,

As proposed by @myshevchuk [here](https://org-roam.discourse.group/t/creating-html-document-notes-with-org-roam-bibtex/396/10), i open a ticket for a change in `orb-preformat-keywords`.

The idea would be to not require the "author" and "editor" fields for `online` entries in a bibtex file. When you keep a web page with Zotero it often has no information in these two fields, which prevents you from creating a note and produces an error message. 

`“Cannot resolve a template to values”`

**Comment by myshevchuk** [comment] 2020-07-16 14:55
You should not see the error now.

Please, do not close the issue yet. The problem was not in `org-roam-bibtex`, the offending function `bibtex-completion-apa-get-value` comes from `bibtex-completion`. The changes I've made should be reverted after the problem is fixed upstream. So I'd like to keep this open as a reminder.

**Comment by bepolymathe** [comment] 2020-07-17 07:20
I did the `org-roam-bibtex` update but I still have the same problem.

**Comment by myshevchuk** [comment] 2020-07-17 07:44
I cannot confirm this with my setup. The note is create without any errors from your bibtex entry.

<img width="1299" alt="Screenshot 2020-07-17 at 09 40 29" src="https://user-images.githubusercontent.com/24212814/87761336-918a9880-c811-11ea-834f-d61741bc068e.png">

Check your installation: unpin `org-roam-bibtex` if you use package pinning, purge the byte-compiled file,  restart Emacs, etc.

**Closed** 2021-05-30 11:33 UTC
